Repository openedx/frontend-lib-content-components, pull requests merged in 2023-12, with the labels that each got.

#403 fix: default display of "Show Answer" and "Show reset option"
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/__snapshots__/index.test.jsx.snap
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/index.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/ResetCard.jsx
  src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/ShowAnswerCard.jsx
  src/editors/data/redux/problem/reducers.js
Labels: open-source-contribution, waiting for eng review

#407 fix: video gallery design fixes
  src/editors/containers/VideoGallery/index.test.jsx
  src/editors/containers/VideoGallery/messages.js
  src/editors/sharedComponents/BaseModal/index.jsx
  src/editors/sharedComponents/SelectionModal/SearchSort.jsx
  src/editors/sharedComponents/SelectionModal/SearchSort.test.jsx
  src/editors/sharedComponents/SelectionModal/index.jsx
  src/editors/sharedComponents/SelectionModal/index.scss
  src/editors/sharedComponents/SelectionModal/messages.js
Labels: waiting on author, open-source-contribution, jira:2u

#410 fix: video editor and uploader layout fixes
  src/editors/Editor.jsx
  src/editors/__snapshots__/Editor.test.jsx.snap
  src/editors/containers/EditorContainer/__snapshots__/index.test.jsx.snap
  src/editors/containers/EditorContainer/index.jsx
  src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoPreviewWidget/index.jsx
  src/editors/containers/VideoGallery/hooks.js
  src/editors/containers/VideoGallery/index.jsx
  src/editors/containers/VideoGallery/index.test.jsx
  src/editors/containers/VideoUploadEditor/VideoUploader.jsx
  src/editors/containers/VideoUploadEditor/__snapshots__/VideoUploader.test.jsx.snap
  src/editors/containers/VideoUploadEditor/__snapshots__/index.test.jsx.snap
  src/editors/containers/VideoUploadEditor/hooks.js
  src/editors/containers/VideoUploadEditor/index.jsx
  src/editors/containers/VideoUploadEditor/index.scss
  src/editors/containers/VideoUploadEditor/index.test.jsx
  src/editors/data/images/videoThumbnail.svg
Labels: open-source-contribution, waiting for eng review, jira:2u

#412 feat: video gallery thumbnail fallback
  src/editors/containers/VideoGallery/index.jsx
  src/editors/sharedComponents/SelectionModal/Gallery.jsx
  src/editors/sharedComponents/SelectionModal/GalleryCard.jsx
  src/editors/sharedComponents/SelectionModal/GalleryCard.test.jsx
  src/editors/sharedComponents/SelectionModal/__snapshots__/GalleryCard.test.jsx.snap
Labels: open-source-contribution, jira:2u
